/**
 * Contract ABIs Configuration
 * 
 * This file will be auto-generated by:
 * pnpm deploy:testnet
 * 
 * After running deployment, the script will copy the ABIs from
 * the compiled artifacts and generate this file.
 * 
 * DO NOT EDIT MANUALLY - Use the deployment script instead.
 */

export const SUBSCRIPTION_MANAGER_ABI = [] as const;

