/**
 * Contract Addresses Configuration
 * 
 * This file will be auto-generated by:
 * pnpm deploy:testnet
 * 
 * After running deployment, the script will update this file with
 * the latest deployed contract addresses.
 * 
 * DO NOT EDIT MANUALLY - Use the deployment script instead.
 */

export const CONTRACT_ADDRESSES = {
  subscriptionManager: '0x0000000000000000000000000000000000000000' as const,
  morphoVault: '0x0000000000000000000000000000000000000000' as const,
} as const;

export const CHAIN_ID = '421614' as const; // Arbitrum Sepolia

